// Alle Dinge, die eingeordnet werden.
// id    → Dateiname des Bildes: bilder/<id>.png
// name  → Text auf der Karte
// motiv → englische Motivbeschreibung für den Flux-Prompt (siehe BILDER.md)
// links / rechts → Begründung, warum genau diese Einordnung RICHTIG ist
//
// WICHTIG: Neue Dinge nur HINTEN anfügen und nichts umsortieren oder löschen.
// Die Teilen-Links codieren die Antworten über die Position in dieser Liste.
window.DINGE = [
  { id: "currywurst-ohne-darm", name: "Currywurst ohne Darm", motiv: "a skinless currywurst cut into slices on a paper tray with a small wooden fork",
    links: "Darm weg, Kompromiss gefunden. So sieht progressive Imbisskultur aus.",
    rechts: "Currywurst ist Kulturerbe. Wer am Darm spart, bewahrt trotzdem Tradition." },
  { id: "lastenrad", name: "Lastenrad", motiv: "a cargo bike with a wooden box in front",
    links: "Kind, Einkauf und Klimaziel in einer Holzkiste. Eindeutiger geht's nicht.",
    rechts: "Eigenes Nutzfahrzeug, eigener Laderaum, keine Hilfe nötig. Purer Mittelstand." },
  { id: "zigaretten-ohne-filter", name: "Zigaretten ohne Filter", motiv: "an open pack of unfiltered cigarettes",
    links: "Hafenkneipe, Streikposten, Arbeiterklasse. Filter sind was für Bosse.",
    rechts: "Keine Filter, keine Vorschriften, keine Diskussion." },
  { id: "veggie-wurst", name: "Vegetarische Wurst", motiv: "a vegetarian sausage on a plate with a sprig of parsley",
    links: "Schmeckt nach Zukunft und ein bisschen nach Erbse.",
    rechts: "Wer Wurst so liebt, dass er sie sogar aus Erbsen nachbaut, ist wertkonservativ." },
  { id: "hafermilch", name: "Hafermilch", motiv: "a carton of oat milk",
    links: "Oat. Flat. White. Mehr muss man dazu nicht sagen.",
    rechts: "Hafer vom heimischen Acker statt Soja aus Übersee. Regional ist konservativ." },
  { id: "grillfleisch", name: "Grillfleisch im Angebot", motiv: "a plastic tray of marinated barbecue meat with a discount sticker",
    links: "Fleisch für alle, egal wie dick das Portemonnaie ist. Sozial gerecht.",
    rechts: "Samstag, Angebot, Grill an. Das ist Deutschland." },
  { id: "tofu", name: "Tofu", motiv: "a block of tofu on a cutting board",
    links: "Ein Block voller Haltung.",
    rechts: "Schnörkellos, diszipliniert, seit 2000 Jahren gleich. Tradition pur." },
  { id: "schnitzel", name: "Schnitzel mit Pommes", motiv: "a schnitzel with french fries and a lemon slice on a plate",
    links: "Das Kantinenessen der Werktätigen seit Generationen.",
    rechts: "Paniert, gebraten, Zitrone drauf. Mehr Ordnung passt nicht auf einen Teller." },
  { id: "doener", name: "Döner", motiv: "a doner kebab wrapped in paper",
    links: "Multikulti im Fladenbrot. Einfacher wird Integration nicht.",
    rechts: "Das deutscheste Gericht der Nachkriegszeit. Heimatküche." },
  { id: "sonntagsbraten", name: "Sonntagsbraten", motiv: "a roast with gravy and dumplings on a plate",
    links: "Die ganze Familie am Tisch, alle kriegen gleich viel Soße. Kollektiv.",
    rechts: "Sonntag, Braten, Klöße, Oma. Da gibt's nichts zu diskutieren." },
  { id: "avocado", name: "Avocado", motiv: "a halved avocado with its pit",
    links: "Grün, weich, auf Toast mit Chili. Ein Bekenntnis.",
    rechts: "Ein Luxusgut mit Kern. Leistung muss sich lohnen." },
  { id: "sauerteigbrot", name: "Sauerteigbrot", motiv: "a round loaf of sourdough bread with a scored top",
    links: "Selbst angesetzt, der Starter hat einen Namen. Gelebte Fürsorge.",
    rechts: "Deutsche Brotkultur, offiziell Kulturerbe. Konservativer wird's nicht." },
  { id: "filterkaffee", name: "Filterkaffee", motiv: "a drip coffee machine with a glass pot",
    links: "Die Kanne im Gewerkschaftsbüro läuft seit 1978.",
    rechts: "Maschine an, Tasse voll, keine Extrawürste." },
  { id: "flat-white", name: "Hafer-Flat-White", motiv: "a latte with leaf foam art in a ceramic cup",
    links: "Hafer, Latte-Art, Laptop mit Stickern. Bilderbuch.",
    rechts: "5,20 Euro für einen Kaffee, und man zahlt es gern. Marktwirtschaft." },
  { id: "mate", name: "Mate", motiv: "a glass bottle of mate soda",
    links: "Der offizielle Treibstoff jedes Plenums.",
    rechts: "Koffein für Leistungsträger, die um drei Uhr nachts noch gründen." },
  { id: "weissbier", name: "Weißbier", motiv: "a tall glass of wheat beer with foam",
    links: "Das Glas ist halb voll, und zwar für alle. Solidarität im Schaum.",
    rechts: "Bayern, Biergarten, Brauchtum. Eindeutig." },
  { id: "naturwein", name: "Naturwein", motiv: "a bottle of natural wine with a hand-drawn label",
    links: "Unfiltriert, trüb, vom Winzerkollektiv. Gut erkannt.",
    rechts: "Wein wie vor 200 Jahren. Mehr Tradition geht nicht." },
  { id: "kraeuterlikoer", name: "Kräuterlikör", motiv: "a small bottle of herbal liqueur",
    links: "Wird auf jeder WG-Party brüderlich geteilt.",
    rechts: "56 Kräuter, eine Heimat, ein Schützenfest." },
  { id: "energydrink", name: "Energydrink", motiv: "a can of energy drink",
    links: "Nachtschicht, Pflege, Lieferdienst. Das Getränk der arbeitenden Menschen.",
    rechts: "Leistung, Motorsport, Flügel. Völlig klar." },
  { id: "kombucha", name: "Kombucha", motiv: "a glass jar of kombucha with a scoby floating in it",
    links: "Im Einmachglas selbst fermentiert. Links, natürlich.",
    rechts: "Eine Pilzkultur, die seit Jahrhunderten gepflegt wird. Wertkonservativ." },
  { id: "suv", name: "SUV", motiv: "a large SUV car, side view",
    links: "Genug Platz, um fünf Nachbarskinder zur Kita mitzunehmen. Sozial.",
    rechts: "Groß, hoch, unaufhaltsam. Glasklar." },
  { id: "diesel-kombi", name: "Diesel-Kombi", motiv: "a station wagon car, side view",
    links: "Das Auto der Handwerker und Pendler. Klassenbewusst.",
    rechts: "400.000 Kilometer ohne Murren. Deutsche Ingenieurskunst." },
  { id: "e-scooter", name: "E-Scooter", motiv: "an electric kick scooter",
    links: "Die Verkehrswende auf zwei kleinen Rädern.",
    rechts: "Start-up, Risikokapital, freie Fahrt. Marktliberal durch und durch." },
  { id: "sportwagen", name: "Sportwagen", motiv: "a classic sports car, side view",
    links: "Kurven, Rebellion, Siebziger. Ein Rennwagen gegen das Spießertum.",
    rechts: "Leistung, Hubraum, Leasingvertrag. Da gibt's nichts zu deuteln." },
  { id: "motorrad", name: "Motorrad", motiv: "a motorcycle, side view",
    links: "Freiheit, Lederjacke, Gegenkultur. Easy Rider war kein Zufall.",
    rechts: "Freiheit, Lederjacke, Landstraße. Pure Selbstbestimmung." },
  { id: "wohnwagen", name: "Wohnwagen", motiv: "a camping caravan with a folding chair in front",
    links: "Tiny House auf Rädern, Gemeinschaft am Campingplatz.",
    rechts: "Eigenes Heim, eigener Stellplatz, eigene Hecke." },
  { id: "nachtzug", name: "Nachtzug", motiv: "a sleeper train carriage at night with a crescent moon",
    links: "Klimafreundlich quer durch Europa. Offensichtlich.",
    rechts: "Schlafwagen wie zu Kaisers Zeiten. Nostalgie ist konservativ." },
  { id: "fahrradhelm", name: "Fahrradhelm", motiv: "a bicycle helmet",
    links: "Verantwortung für die Gemeinschaft, auch auf dem Kopf.",
    rechts: "Sicherheit, Ordnung, Vorsorge. Ganz klar." },
  { id: "jutebeutel", name: "Jutebeutel", motiv: "a cotton tote bag",
    links: "Mit Aufdruck vom unabhängigen Buchladen. Zweifellos.",
    rechts: "Den hatte schon Oma auf dem Wochenmarkt. Tradition." },
  { id: "birkenstock", name: "Birkenstock", motiv: "a pair of cork footbed sandals",
    links: "Bequem, erdverbunden, ein Statement an jedem Fuß.",
    rechts: "Seit Generationen unverändert. Deutsche Wertarbeit." },
  { id: "barfussschuhe", name: "Barfußschuhe", motiv: "a pair of minimalist barefoot shoes with separate toes",
    links: "Erdung mit Mutter Natur. Selbstverständlich.",
    rechts: "Zurück zu den Wurzeln. Konservativ im Wortsinn." },
  { id: "adiletten", name: "Adiletten mit Tennissocken", motiv: "slide sandals worn with white tennis socks",
    links: "Im Freibad sind alle gleich. Klassenlose Mode.",
    rechts: "Feierabend, Terrasse, Rasensprenger. Deutscher geht's nicht." },
  { id: "trachtenjanker", name: "Trachtenjanker", motiv: "a traditional Bavarian wool jacket with horn buttons",
    links: "Vom Flohmarkt, mit Vintage-Charme. Ironisch getragen, also links.",
    rechts: "Heimat zum Anziehen. Offensichtlich." },
  { id: "latzhose", name: "Latzhose", motiv: "a pair of dungarees",
    links: "Wer Latzhose trägt, hat mindestens einen Workshop geleitet.",
    rechts: "Handwerk, Bauernhof, ehrliche Arbeit." },
  { id: "karohemd", name: "Karohemd", motiv: "a checkered flannel shirt",
    links: "Holzfäller, Grunge, Kollektivcafé. Eindeutig.",
    rechts: "Holzfäller, Jagdhütte, Baumarkt. Eindeutig." },
  { id: "wachsjacke", name: "Wachsjacke", motiv: "a quilted waxed country jacket with a corduroy collar",
    links: "Gewachst statt weggeworfen. Reparieren ist politisch.",
    rechts: "Landsitz, Hund, Nieselregen. Keine Frage." },
  { id: "vollbart", name: "Vollbart", motiv: "a man's face with a full beard",
    links: "Marx hatte einen. Fall abgeschlossen.",
    rechts: "Förster, Seemann, Familienoberhaupt. Der Bart spricht für sich." },
  { id: "schnauzbart", name: "Schnauzbart", motiv: "a man's face with a thick moustache",
    links: "Siebziger, Gewerkschaft, Arbeitskampf.",
    rechts: "Stammtisch, Schützenkönig, Ordnungsamt." },
  { id: "undercut", name: "Undercut", motiv: "a head seen from behind with an undercut hairstyle",
    links: "Friseur in Kreuzberg, Hafer-Latte in der Hand.",
    rechts: "Pflegeleicht, ordentlich, jeden Morgen gleich." },
  { id: "hornbrille", name: "Hornbrille", motiv: "a pair of thick-rimmed glasses",
    links: "Belesen, intellektuell, mindestens ein Seminar über Adorno.",
    rechts: "Notar, Oberstudienrat, Hausverwaltung." },
  { id: "tattoo", name: "Tattoo", motiv: "a tattooed forearm",
    links: "Selbstbestimmung über den eigenen Körper.",
    rechts: "Anker, Rose, Mama. Traditionsbewusst." },
  { id: "gartenzwerg", name: "Gartenzwerg", motiv: "a garden gnome",
    links: "Klein, rote Mütze, arbeitet ohne Pause. Proletariat.",
    rechts: "Wacht über Beet und Grundstücksgrenze. Völlig klar." },
  { id: "schrebergarten", name: "Schrebergarten", motiv: "a small allotment garden with a hut and a picket fence",
    links: "Gemeinschaftlich gärtnern und selbst versorgen. Urban Gardening, nur älter.",
    rechts: "Satzung, Heckenhöhe, Vereinsvorstand." },
  { id: "englischer-rasen", name: "Englischer Rasen", motiv: "a perfectly striped lawn with a lawnmower",
    links: "Ein gepflegter Gemeinschaftsraum für alle Kinder der Straße.",
    rechts: "Streifen im Zentimetertakt. Ordnung ist das halbe Leben." },
  { id: "bluehwiese", name: "Blühwiese", motiv: "a wildflower meadow",
    links: "Artenvielfalt, Insektenschutz, Anarchie im Beet.",
    rechts: "Die Wiese, wie sie früher war. Bewahrend im besten Sinn." },
  { id: "maehroboter", name: "Mähroboter", motiv: "a robotic lawn mower on grass",
    links: "Automatisierung, damit Menschen frei sind. Voll links.",
    rechts: "Mäht, während man Wichtigeres tut. Eigentum arbeitet." },
  { id: "kaminofen", name: "Kaminofen", motiv: "a wood-burning stove with stacked logs",
    links: "Wärme im Kreis, Gespräche bis spät. Lagerfeuer-Sozialismus.",
    rechts: "Holz aus dem eigenen Wald. Unabhängigkeit." },
  { id: "waermepumpe", name: "Wärmepumpe", motiv: "an outdoor heat pump unit next to a house wall",
    links: "Die Energiewende im Vorgarten.",
    rechts: "Senkt die Nebenkosten. Wer rechnen kann, weiß Bescheid." },
  { id: "balkonkraftwerk", name: "Balkonkraftwerk", motiv: "a solar panel mounted on a balcony railing",
    links: "Energiewende von unten.",
    rechts: "Unabhängig vom Staat, Strom vom eigenen Balkon. Libertär." },
  { id: "gasgrill", name: "Gasgrill", motiv: "a large gas barbecue grill",
    links: "Grillen ohne Qualm, für die ganze Nachbarschaft.",
    rechts: "Knopf drücken, Hitze da. Effizienz." },
  { id: "muelltrennung", name: "Mülltrennung", motiv: "three recycling bins side by side",
    links: "Umweltschutz, logisch.",
    rechts: "Gelb, Blau, Braun, Grau. Deutsche Ordnung in vier Tonnen." },
  { id: "reihenhaus", name: "Reihenhaus", motiv: "a row of identical terraced houses",
    links: "Gleiche Häuser für alle. Klingt nach Utopie.",
    rechts: "Eigenheim, Carport, Hecke. Logisch." },
  { id: "altbauwohnung", name: "Altbauwohnung", motiv: "the facade of an old apartment building with stucco and tall windows",
    links: "Dielen, Stuck, WG mit acht Leuten.",
    rechts: "Stuck, hohe Decken, Gründerzeit. Wer Altbau liebt, liebt Tradition." },
  { id: "wg-kueche", name: "WG-Küche", motiv: "a messy shared kitchen with a cleaning rota on the wall",
    links: "Gemeinschaftseigentum, Putzplan, Plenum.",
    rechts: "Putzplan! Regeln! Wer drückt sich? Das ist Ordnung." },
  { id: "bausparvertrag", name: "Bausparvertrag", motiv: "a small house-shaped piggy bank with a coin",
    links: "Solidarisch sparen, erfunden als Gemeinschaftsidee.",
    rechts: "Vorsorge, Eigenheim, Zinsen. Glasklar." },
  { id: "baumarkt", name: "Baumarkt am Samstag", motiv: "a shopping cart full of lumber and tools",
    links: "Selber machen statt kaufen. Unabhängig vom Kapital.",
    rechts: "Samstag, Dübel, Schlagbohrmaschine." },
  { id: "holzspielzeug", name: "Holzspielzeug", motiv: "wooden toy blocks and a small wooden train",
    links: "Nachhaltig, plastikfrei, Waldorf. Eindeutig.",
    rechts: "Wie früher, als Kinder noch mit Bauklötzen spielten." },
  { id: "schallplatten", name: "Schallplatten", motiv: "a record player with a vinyl record",
    links: "Aus der Plattenkiste des Kollektivs.",
    rechts: "Analog, wertbeständig, früher war alles besser." },
  { id: "yoga", name: "Yoga", motiv: "a person in a yoga pose on a mat",
    links: "Achtsamkeit, Klangschale, Gemeinschaft.",
    rechts: "Disziplin und Selbstoptimierung, jeden Morgen um sechs." },
  { id: "crossfit", name: "Crossfit", motiv: "a person lifting a kettlebell",
    links: "Gemeinsam schwitzen, sich gegenseitig anfeuern. Solidarität.",
    rechts: "Leistung, Wettkampf, Bestzeit. Klar." },
  { id: "angeln", name: "Angeln", motiv: "a fishing rod and a bucket at the edge of a lake",
    links: "Stille, Natur, Entschleunigung.",
    rechts: "Angelschein, Vereinsheim, Petri Heil." },
  { id: "jagd", name: "Jagd", motiv: "a wooden hunting high seat at the edge of a forest",
    links: "Wildtiermanagement für den Artenschutz. Ökologisch durch und durch.",
    rechts: "Hochsitz, Hund, Hubertusmesse. Offensichtlich." },
  { id: "wandern", name: "Wandern", motiv: "hiking boots and a walking stick",
    links: "Die Naturfreunde wurden 1895 von Arbeitern gegründet. Historisch belegt.",
    rechts: "Heimat erkunden, Gipfelkreuz, Wanderlied." },
  { id: "stadion", name: "Fußball im Stadion", motiv: "football fans in a stadium holding up scarves",
    links: "Arbeitersport, Fankurve, Gemeinschaft.",
    rechts: "Vereinstreue, Hymne, Tradition." },
  { id: "tatort", name: "Tatort am Sonntag", motiv: "a sofa facing a television in a living room at night",
    links: "Sonntagabend-Sozialkritik mit Kommissar.",
    rechts: "Sonntag, 20:15 Uhr, Sofa. Jede Woche gleich." },
  { id: "schlager", name: "Schlager", motiv: "a vintage microphone with a small heart",
    links: "Musik für alle, ohne Eintrittskarte fürs Feuilleton. Volksnah.",
    rechts: "Herz, Heimat, Hitparade." },
  { id: "techno", name: "Techno", motiv: "a DJ mixer between two turntables",
    links: "Berliner Club, alle gleich auf der Tanzfläche.",
    rechts: "Vier Viertel, immer im Takt, keine Abweichungen." },
  { id: "punk", name: "Punk", motiv: "a studded leather jacket with patches",
    links: "Gegen alles. Also auch dagegen. Eindeutig.",
    rechts: "No Future, keine Regeln, kein Staat. Libertär bis ins Mark." },
  { id: "heavy-metal", name: "Heavy Metal", motiv: "a flying V electric guitar",
    links: "Lange Haare, Kutte, Gemeinschaft im Schlamm von Wacken.",
    rechts: "Laut, hart, heldenhaft." },
  { id: "volksmusik", name: "Volksmusik", motiv: "an accordion",
    links: "Musik aus dem Volk, für das Volk. Steht ja schon im Namen.",
    rechts: "Akkordeon, Tracht, Musikantenstadl." },
  { id: "schuetzenfest", name: "Schützenfest", motiv: "a traditional marksmen's hat decorated with feathers and medals",
    links: "Das ganze Dorf feiert zusammen. Kollektiv.",
    rechts: "Schützenkönig, Umzug, Uniform." },
  { id: "boeller", name: "Silvesterböller", motiv: "a pile of firecrackers",
    links: "Anarchie für eine Nacht.",
    rechts: "Seit Jahrhunderten Brauch, um böse Geister zu vertreiben." },
  { id: "lagerfeuer", name: "Lagerfeuer", motiv: "a campfire with logs",
    links: "Alle im Kreis, Gitarre, Gesang.",
    rechts: "Pfadfinder, Stockbrot, Tradition." },
  { id: "festival", name: "Festival", motiv: "a small tent at a music festival with a flag",
    links: "Zelte, Teilen, Freiheit, Matsch.",
    rechts: "VIP-Bändchen, eigener Pavillon, eigene Box." },
  { id: "schaeferhund", name: "Schäferhund", motiv: "a German shepherd dog sitting",
    links: "Treu, loyal, zuverlässig. Eine Gewerkschaft auf vier Pfoten.",
    rechts: "Hundeplatz, Gehorsam, Ordnung. Völlig richtig." },
  { id: "franzoesische-bulldogge", name: "Französische Bulldogge", motiv: "a French bulldog sitting",
    links: "Klein, stur, die Revolution im Blut.",
    rechts: "Rassehund mit eigenem Instagram-Account." },
  { id: "katze", name: "Katze", motiv: "a cat curled up asleep",
    links: "Keine Herren, keine Befehle. Anarchistin.",
    rechts: "Verteidigt ihr Revier und gehorcht niemandem." }
];
