// Alle Dinge, die eingeordnet werden.
// id    → Dateiname des Bildes: bilder/<id>.png
// name  → Text auf der Karte
// motiv → englische Motivbeschreibung für den Flux-Prompt (siehe BILDER.md)
//
// WICHTIG: Neue Dinge nur HINTEN anfügen und nichts umsortieren oder löschen.
// Die Teilen-Links codieren die Antworten über die Position in dieser Liste.
window.DINGE = [
  { id: "currywurst-ohne-darm", name: "Currywurst ohne Darm", motiv: "a skinless currywurst cut into slices on a paper tray with a small wooden fork" },
  { id: "lastenrad", name: "Lastenrad", motiv: "a cargo bike with a wooden box in front" },
  { id: "zigaretten-ohne-filter", name: "Zigaretten ohne Filter", motiv: "an open pack of unfiltered cigarettes" },
  { id: "veggie-wurst", name: "Vegetarische Wurst", motiv: "a vegetarian sausage on a plate with a sprig of parsley" },
  { id: "hafermilch", name: "Hafermilch", motiv: "a carton of oat milk" },
  { id: "grillfleisch", name: "Grillfleisch im Angebot", motiv: "a plastic tray of marinated barbecue meat with a discount sticker" },
  { id: "tofu", name: "Tofu", motiv: "a block of tofu on a cutting board" },
  { id: "schnitzel", name: "Schnitzel mit Pommes", motiv: "a schnitzel with french fries and a lemon slice on a plate" },
  { id: "doener", name: "Döner", motiv: "a doner kebab wrapped in paper" },
  { id: "sonntagsbraten", name: "Sonntagsbraten", motiv: "a roast with gravy and dumplings on a plate" },
  { id: "avocado", name: "Avocado", motiv: "a halved avocado with its pit" },
  { id: "sauerteigbrot", name: "Sauerteigbrot", motiv: "a round loaf of sourdough bread with a scored top" },
  { id: "filterkaffee", name: "Filterkaffee", motiv: "a drip coffee machine with a glass pot" },
  { id: "flat-white", name: "Hafer-Flat-White", motiv: "a latte with leaf foam art in a ceramic cup" },
  { id: "mate", name: "Mate", motiv: "a glass bottle of mate soda" },
  { id: "weissbier", name: "Weißbier", motiv: "a tall glass of wheat beer with foam" },
  { id: "naturwein", name: "Naturwein", motiv: "a bottle of natural wine with a hand-drawn label" },
  { id: "kraeuterlikoer", name: "Kräuterlikör", motiv: "a small bottle of herbal liqueur" },
  { id: "energydrink", name: "Energydrink", motiv: "a can of energy drink" },
  { id: "kombucha", name: "Kombucha", motiv: "a glass jar of kombucha with a scoby floating in it" },
  { id: "suv", name: "SUV", motiv: "a large SUV car, side view" },
  { id: "diesel-kombi", name: "Diesel-Kombi", motiv: "a station wagon car, side view" },
  { id: "e-scooter", name: "E-Scooter", motiv: "an electric kick scooter" },
  { id: "sportwagen", name: "Sportwagen", motiv: "a classic sports car, side view" },
  { id: "motorrad", name: "Motorrad", motiv: "a motorcycle, side view" },
  { id: "wohnwagen", name: "Wohnwagen", motiv: "a camping caravan with a folding chair in front" },
  { id: "nachtzug", name: "Nachtzug", motiv: "a sleeper train carriage at night with a crescent moon" },
  { id: "fahrradhelm", name: "Fahrradhelm", motiv: "a bicycle helmet" },
  { id: "jutebeutel", name: "Jutebeutel", motiv: "a cotton tote bag" },
  { id: "birkenstock", name: "Birkenstock", motiv: "a pair of cork footbed sandals" },
  { id: "barfussschuhe", name: "Barfußschuhe", motiv: "a pair of minimalist barefoot shoes with separate toes" },
  { id: "adiletten", name: "Adiletten mit Tennissocken", motiv: "slide sandals worn with white tennis socks" },
  { id: "trachtenjanker", name: "Trachtenjanker", motiv: "a traditional Bavarian wool jacket with horn buttons" },
  { id: "latzhose", name: "Latzhose", motiv: "a pair of dungarees" },
  { id: "karohemd", name: "Karohemd", motiv: "a checkered flannel shirt" },
  { id: "wachsjacke", name: "Wachsjacke", motiv: "a quilted waxed country jacket with a corduroy collar" },
  { id: "vollbart", name: "Vollbart", motiv: "a man's face with a full beard" },
  { id: "schnauzbart", name: "Schnauzbart", motiv: "a man's face with a thick moustache" },
  { id: "undercut", name: "Undercut", motiv: "a head seen from behind with an undercut hairstyle" },
  { id: "hornbrille", name: "Hornbrille", motiv: "a pair of thick-rimmed glasses" },
  { id: "tattoo", name: "Tattoo", motiv: "a tattooed forearm" },
  { id: "gartenzwerg", name: "Gartenzwerg", motiv: "a garden gnome" },
  { id: "schrebergarten", name: "Schrebergarten", motiv: "a small allotment garden with a hut and a picket fence" },
  { id: "englischer-rasen", name: "Englischer Rasen", motiv: "a perfectly striped lawn with a lawnmower" },
  { id: "bluehwiese", name: "Blühwiese", motiv: "a wildflower meadow" },
  { id: "maehroboter", name: "Mähroboter", motiv: "a robotic lawn mower on grass" },
  { id: "kaminofen", name: "Kaminofen", motiv: "a wood-burning stove with stacked logs" },
  { id: "waermepumpe", name: "Wärmepumpe", motiv: "an outdoor heat pump unit next to a house wall" },
  { id: "balkonkraftwerk", name: "Balkonkraftwerk", motiv: "a solar panel mounted on a balcony railing" },
  { id: "gasgrill", name: "Gasgrill", motiv: "a large gas barbecue grill" },
  { id: "muelltrennung", name: "Mülltrennung", motiv: "three recycling bins side by side" },
  { id: "reihenhaus", name: "Reihenhaus", motiv: "a row of identical terraced houses" },
  { id: "altbauwohnung", name: "Altbauwohnung", motiv: "the facade of an old apartment building with stucco and tall windows" },
  { id: "wg-kueche", name: "WG-Küche", motiv: "a messy shared kitchen with a cleaning rota on the wall" },
  { id: "bausparvertrag", name: "Bausparvertrag", motiv: "a small house-shaped piggy bank with a coin" },
  { id: "baumarkt", name: "Baumarkt am Samstag", motiv: "a shopping cart full of lumber and tools" },
  { id: "holzspielzeug", name: "Holzspielzeug", motiv: "wooden toy blocks and a small wooden train" },
  { id: "schallplatten", name: "Schallplatten", motiv: "a record player with a vinyl record" },
  { id: "yoga", name: "Yoga", motiv: "a person in a yoga pose on a mat" },
  { id: "crossfit", name: "Crossfit", motiv: "a person lifting a kettlebell" },
  { id: "angeln", name: "Angeln", motiv: "a fishing rod and a bucket at the edge of a lake" },
  { id: "jagd", name: "Jagd", motiv: "a wooden hunting high seat at the edge of a forest" },
  { id: "wandern", name: "Wandern", motiv: "hiking boots and a walking stick" },
  { id: "stadion", name: "Fußball im Stadion", motiv: "football fans in a stadium holding up scarves" },
  { id: "tatort", name: "Tatort am Sonntag", motiv: "a sofa facing a television in a living room at night" },
  { id: "schlager", name: "Schlager", motiv: "a vintage microphone with a small heart" },
  { id: "techno", name: "Techno", motiv: "a DJ mixer between two turntables" },
  { id: "punk", name: "Punk", motiv: "a studded leather jacket with patches" },
  { id: "heavy-metal", name: "Heavy Metal", motiv: "a flying V electric guitar" },
  { id: "volksmusik", name: "Volksmusik", motiv: "an accordion" },
  { id: "schuetzenfest", name: "Schützenfest", motiv: "a traditional marksmen's hat decorated with feathers and medals" },
  { id: "boeller", name: "Silvesterböller", motiv: "a pile of firecrackers" },
  { id: "lagerfeuer", name: "Lagerfeuer", motiv: "a campfire with logs" },
  { id: "festival", name: "Festival", motiv: "a small tent at a music festival with a flag" },
  { id: "schaeferhund", name: "Schäferhund", motiv: "a German shepherd dog sitting" },
  { id: "franzoesische-bulldogge", name: "Französische Bulldogge", motiv: "a French bulldog sitting" },
  { id: "katze", name: "Katze", motiv: "a cat curled up asleep" }
];
